<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-8T0TF8I" failures="2" tests="2" name="com.runner.TestRunner" time="30.128" errors="0" timestamp="22 Mar 2023 05:50:18 GMT" skipped="0">
  <testcase classname="com.runner.TestRunner" name="runScenario" time="14.029">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.steps.StepDefinition.user_verify_the_error_message(StepDefinition.java:54)
at ✽.User verify the error message(file:src/test/resources/features/loginpage.feature:12)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="com.runner.TestRunner" name="runScenario" time="16.099">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.steps.StepDefinition.user_verify_the_error_message(StepDefinition.java:54)
at ✽.User verify the error message(file:src/test/resources/features/loginpage.feature:12)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- com.runner.TestRunner -->
